name: Build CircuitPython Pico Mouse UF2

on: workflow_dispatch

jobs:
  build_pico:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CircuitPython source
        uses: actions/checkout@v3
        with:
          repository: adafruit/circuitpython
          submodules: recursive

      - name: Install dependencies (Python + tools)
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip make cmake ninja-build libusb-1.0-0-dev
          python3 -m pip install --upgrade pip
          pip install cascadetoml

      - name: Install latest Arm GCC toolchain (version 14)
        run: |
          wget -q https://developer.arm.com/-/media/Files/downloads/gnu-rm/14.0.Rel1/gcc-arm-none-eabi-14.0.rel1-x86_64-linux.tar.bz2
          tar -xjf gcc-arm-none-eabi-14.0.rel1-x86_64-linux.tar.bz2
          echo "$PWD/gcc-arm-none-eabi-14.0.rel1-x86_64-linux/bin" >> $GITHUB_PATH

      - name: Modify USB descriptor (Mouse only)
        run: |
          sed -i 's/USB_PRODUCT = .*/USB_PRODUCT = "Mouse"/' ports/raspberrypi/boards/raspberry_pi_pico/mpconfigboard.mk
          sed -i 's/USB_MANUFACTURER = .*/USB_MANUFACTURER = "Generic"/' ports/raspberrypi/boards/raspberry_pi_pico/mpconfigboard.mk

      - name: Fetch version tags
        run: make fetch-tags

      - name: Build firmware
        run: make -C ports/raspberrypi BOARD=raspberry_pi_pico

      - name: Upload UF2 firmware
        uses: actions/upload-artifact@v4
        with:
          name: pico-mouse-firmware
          path: ports/raspberrypi/build-raspberry_pi_pico/firmware.uf2
