name: Build CircuitPython Pico Mouse UF2

on: workflow_dispatch

jobs:
  build_pico:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CircuitPython source
        uses: actions/checkout@v3
        with:
          repository: adafruit/circuitpython
          submodules: recursive

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip make cmake ninja-build libusb-1.0-0-dev

      - name: Install Python build tools
        run: |
          python3 -m pip install --upgrade pip
          pip install cascadetoml

      - name: Install ARM GCC Toolchain (official v14.2)
        run: |
          wget https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/releases/download/llvm-14.2.rel1/LLVMEmbeddedToolchainForArm-14.2.rel1-linux-x86_64.tar.gz -O toolchain.tar.gz
          mkdir -p toolchain
          tar -xzf toolchain.tar.gz -C toolchain --strip-components=1
          echo "$PWD/toolchain/bin" >> $GITHUB_PATH
          rm toolchain.tar.gz

      - name: Modify USB descriptor (Custom HID Name)
        run: |
          sed -i 's/^USB_PRODUCT = .*/USB_PRODUCT = "Mouse"/' ports/raspberrypi/boards/raspberry_pi_pico/mpconfigboard.mk
          sed -i 's/^USB_MANUFACTURER = .*/USB_MANUFACTURER = "Generic"/' ports/raspberrypi/boards/raspberry_pi_pico/mpconfigboard.mk

      - name: Fetch version tags
        run: make fetch-tags

      - name: Build CircuitPython firmware for Pico
        run: make -C ports/raspberrypi BOARD=raspberry_pi_pico

      - name: Upload UF2 firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: pico-mouse-firmware
          path: ports/raspberrypi/build-raspberry_pi_pico/firmware.uf2
