name: Build CircuitPython Pico Mouse UF2

on: workflow_dispatch

jobs:
  build_pico:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: adafruit/circuitpython
          submodules: recursive

      - name: Install toolchain
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi libnewlib-arm-none-eabi make python3

      - name: Modify USB descriptor
        run: |
          sed -i 's/USB_PRODUCT = .*/USB_PRODUCT = "Mouse"/' ports/raspberrypi/boards/raspberry_pi_pico/mpconfigboard.mk
          sed -i 's/USB_MANUFACTURER = .*/USB_MANUFACTURER = "Generic"/' ports/raspberrypi/boards/raspberry_pi_pico/mpconfigboard.mk

      - name: Fetch version tags
        run: make fetch-tags

      - name: Build firmware
        run: make -C ports/raspberrypi BOARD=raspberry_pi_pico

      - name: Upload UF2
        uses: actions/upload-artifact@v4
        with:
          name: pico-mouse-firmware
          path: ports/raspberrypi/build-raspberry_pi_pico/firmware.uf2
